### ISSUE TITLE
Hot Reload Broken

### ISSUE THREAD

**Issue by caseyjkey** [zankhq/astro-starter#10]
I cloned the repository, ran `pnpm install` then `pnpm dev`. The site builds and says " [content] Watching src/content/ for changes" However, changes made within src/content does not trigger a refresh. Manual refreshing shows stale content. I also expect changes to components to trigger a refresh with changes, but nothing happens. This slows development significantly.

**Comment by zanhk** [comment]
Hi @caseyjkey I could not reproduce the error, can you provide some more info like os, node versions, other significan info.

Also I updated all dependencies, can you check if you still encounter the error with the new udpate?

**Comment by caseyjkey** [comment]
This was on Windows using WSL2 and Node v19.8.1. Switching to Git Bash and installing Node for Windows resolved this issue.
