### ISSUE TITLE
pnpm build causes issue with Sharp

### ISSUE THREAD

**Issue by Divinely5782** [zankhq/astro-starter#27]
Error: Could not load the "sharp" module using the win32-x64 runtime.

I cant build project, because of rhis error. Does build process work on your machine?

**Comment by zanhk** [comment]
Hi, should be fixed now, 

try 

`bun install`

`bun run dev`

**Comment by Divinely5782** [comment]
So the only solution is to use bun? 😯

I started Astro project from scratch and sharp builds everything fine.

**Comment by zanhk** [comment]
no, you should be able to use npm or pnpm as well

**Comment by zanhk** [comment]
Just tested and can confirm it works with npm
